// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBLyuhpPh0QHJ1jQeejKaNoof3AG2qot0',
    appId: '1:227770592058:web:bc61cf318c1336a26e7e03',
    messagingSenderId: '227770592058',
    projectId: 'push-notifications-91662',
    authDomain: 'push-notifications-91662.firebaseapp.com',
    storageBucket: 'push-notifications-91662.appspot.com',
    measurementId: 'G-57CT39F5TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKpG-SA93vW3ARgJH00Lsih_fkNL8Ws7I',
    appId: '1:227770592058:android:e5df4d646d12d69f6e7e03',
    messagingSenderId: '227770592058',
    projectId: 'push-notifications-91662',
    storageBucket: 'push-notifications-91662.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8cUe-2XLxJTPnFtIp6xivt7H1M42zphI',
    appId: '1:227770592058:ios:49db547a3de481686e7e03',
    messagingSenderId: '227770592058',
    projectId: 'push-notifications-91662',
    storageBucket: 'push-notifications-91662.appspot.com',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8cUe-2XLxJTPnFtIp6xivt7H1M42zphI',
    appId: '1:227770592058:ios:1370648764124e8c6e7e03',
    messagingSenderId: '227770592058',
    projectId: 'push-notifications-91662',
    storageBucket: 'push-notifications-91662.appspot.com',
    iosBundleId: 'com.example.pushNotifications.RunnerTests',
  );
}
